# Generated by Django 3.2.9 on 2021-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_section',
            name='image',
            field=models.ImageField(default=0, upload_to='Pictures'),
            preserve_default=False,
        ),
    ]
