# Generated by Django 3.2.9 on 2021-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('intro', models.TextField()),
                ('jobtitle', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('birthday', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('freelance', models.BooleanField()),
                ('sumsary', models.TextField()),
            ],
        ),
    ]
